// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC84unEEBRgF_9g_xCzAsJA14CWiRQ0Mko',
    appId: '1:392439953965:web:c8fe371aaac20c2b1996a4',
    messagingSenderId: '392439953965',
    projectId: 'companion-741ca',
    authDomain: 'companion-741ca.firebaseapp.com',
    storageBucket: 'companion-741ca.firebasestorage.app',
    measurementId: 'G-M4MXX9E2XM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCVAHeQpqa9IKWLwq8IqlMNKqQVN_C9AY',
    appId: '1:392439953965:ios:6235cd9c834c18471996a4',
    messagingSenderId: '392439953965',
    projectId: 'companion-741ca',
    storageBucket: 'companion-741ca.firebasestorage.app',
    iosBundleId: 'com.example.companionMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC84unEEBRgF_9g_xCzAsJA14CWiRQ0Mko',
    appId: '1:392439953965:web:2efe9aa0e0cd55ff1996a4',
    messagingSenderId: '392439953965',
    projectId: 'companion-741ca',
    authDomain: 'companion-741ca.firebaseapp.com',
    storageBucket: 'companion-741ca.firebasestorage.app',
    measurementId: 'G-6RY7L3J4R3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCVAHeQpqa9IKWLwq8IqlMNKqQVN_C9AY',
    appId: '1:392439953965:ios:6235cd9c834c18471996a4',
    messagingSenderId: '392439953965',
    projectId: 'companion-741ca',
    storageBucket: 'companion-741ca.firebasestorage.app',
    iosBundleId: 'com.example.companionMobile',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmVeWBxYMjspuqTNwnz0c3pqMPZGVdL_4',
    appId: '1:392439953965:android:2194bbb79a15f4771996a4',
    messagingSenderId: '392439953965',
    projectId: 'companion-741ca',
    storageBucket: 'companion-741ca.firebasestorage.app',
  );

}